-- Find the item that has the minimum weight
SELECT ITEMNO, DESCRIPTION, WEIGHT
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- Find the different warehouses in "Pune"
SELECT DISTINCT WID, WNAME
FROM WAREHOUSES
WHERE LOCATION = 'Pune';

-- Find the details of items ordered by a customer named "Mr. Patil"
SELECT C.CNAME, O.ONO, I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CNO
JOIN ORDERS_ITEMS OI ON O.ONO = OI.ONO
JOIN ITEMS I ON OI.ITEMNO = I.ITEMNO
WHERE C.CNAME = 'Mr. Patil';

-- Find a Warehouse that has the maximum number of stores
SELECT WID, WNAME
FROM WAREHOUSES
WHERE WID = (SELECT WID FROM STORES GROUP BY WID HAVING COUNT(*) = MAX(COUNT(*)));

-- Find an item that is ordered for a minimum number of times
SELECT I.ITEMNO, I.DESCRIPTION, COUNT(OI.ONO) AS ORDER_COUNT
FROM ITEMS I
LEFT JOIN ORDERS_ITEMS OI ON I.ITEMNO = OI.ITEMNO
GROUP BY I.ITEMNO, I.DESCRIPTION
HAVING ORDER_COUNT = (SELECT MIN(ORDER_COUNT) FROM (SELECT COUNT(ONO) AS ORDER_COUNT FROM ORDERS_ITEMS GROUP BY ITEMNO) AS T);

-- Find the detailed orders given by each customer
SELECT C.CNO, C.CNAME, O.ONO, O.ODATE, I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
LEFT JOIN ORDERS O ON C.CNO = O.CNO
LEFT JOIN ORDERS_ITEMS OI ON O.ONO = OI.ONO
LEFT JOIN ITEMS I ON OI.ITEMNO = I.ITEMNO;
